apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: backend # Кладем в папку backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: hashicorp/http-echo
        args: ["-text", "Hello from Backend API!"]
        resources:
          requests: { memory: "16Mi", cpu: "10m" }
