apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: structural-root-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/anastasiyadubrouskaya/my-gitops-test.git'
    targetRevision: HEAD
    path: my-cluster-structure
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
