apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-server
  namespace: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - name: api
        image: hashicorp/http-echo:latest
        # Контейнер будет слушать порт 5678 и отвечать на любой запрос
        args: ["-text", "Hello from Backend API!", "-listen", ":5678"]
        ports:
        - containerPort: 5678
        # Рабочая liveness проба
        livenessProbe:
          httpGet:
            path: /
            port: 5678
          initialDelaySeconds: 3
          periodSeconds: 5
        readinessProbe:
          tcpSocket:
            port: 5678
          initialDelaySeconds: 3
          periodSeconds: 5
        resources:
          requests:
            memory: "16Mi"
            cpu: "10m"
          limits:
            memory: "32Mi"
            cpu: "50m"
