apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-kafka
  namespace: argocd # Application всегда живет в системном неймспейсе Argo CD
spec:
  project: default

  # БЛОК 1: ОТКУДА БРАТЬ ЧАРТ?
  source:
    repoURL: 'https://charts.bitnami.com/bitnami' # URL официального репозитория Bitnami
    chart: kafka                                  # Имя чарта
    targetRevision: 26.x.x                        # Версия чарта (всегда фиксируем!)

    # КАК ПЕРЕДАТЬ НАШИ НАСТРОЙКИ В ЧУЖОЙ ЧАРТ?
    helm:
      valueFiles:
        # Мы говорим Argo CD: "Скачай чарт у Bitnami, но настройки (values) 
        # возьми из нашего Git-репозитория по вот этой ссылке"
        - https://raw.githubusercontent.com/my-org/my-gitops-repo/main/envs/kafka-values.yaml

  # БЛОК 2: КУДА СТАВИТЬ?
  destination:
    server: 'https://kubernetes.default.svc' # Ставим в тот же кластер, где живет сам Argo CD
    namespace: data-platform                 # Наш выделенный неймспейс для данных

  # БЛОК 3: КАК СИНХРОНИЗИРОВАТЬ?
  syncPolicy:
    automated:
      prune: true     # Если мы удалим Application из Git, Argo удалит Кафку из кластера.
      selfHeal: true  # Если дата-инженер случайно удалит под Кафки руками (через kubectl delete pod), Argo мгновенно это заметит и создаст его заново.
    syncOptions:
      - CreateNamespace=true # Если неймспейса data-platform еще нет — создай его.
