apiVersion: v1
kind: ConfigMap
metadata:
  name: locust-script
  namespace: app-prod
data:
  # Индустриальный чарт Locust ожидает, что файл будет называться main.py
  main.py: |
    from locust import HttpUser, task, between
    class WebsiteUser(HttpUser):
        wait_time = between(1, 2)
        @task
        def index_page(self):
            self.client.get("/")
