name: Helm CI

# Пайплайн запускается при каждом пуше в ветку main
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      # 1. Скачиваем твой код на сервер GitHub
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Устанавливаем утилиту Helm
      - name: Install Helm
        uses: azure/setup-helm@v4.2.0
        with:
          version: v3.14.3

      # 3. Проверяем синтаксис твоего чарта на ошибки (Линтинг)
      - name: Run Helm Lint
        run: helm lint .

      # 4. Пробуем сгенерировать финальные манифесты (чтобы убедиться, что шаблоны работают)
      - name: Run Helm Template
        run: helm template my-test-release .
